$(document).ready(function () {

    //call the function when load the page (prevent see the back of the card "anwsers")
    flipcard();

    // Put all necessary Event Listeners below here //
    //////////////////////////////////////////////////

    //Load the questions and turn off Carousel

    $("#btnStart").click(function(){ 
        triviaDB();
        $("#myCarousel").empty();
        $("#card-questions-container").empty();
    });
    
    
    //bind functionality to sidebar
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
        $(this).toggleClass('active');
    });

    document.addEventListener('input', function (event) {
        if (event.target.tagName.toLowerCase() !== 'textarea') return;
        autoExpand(event.target);
    }, false);

    //event click on question card controlling the flip
    $(".card-question").click(function(){ flipcard() }) ;  

    $(document).on("click", ".questionTypeRadio", renderAnswerInputs)
});


var autoExpand = function (field) {

	// Reset field height
	field.style.height = 'inherit';

	// Get the computed styles for the element
	var computed = window.getComputedStyle(field);

	// Calculate the height
	var height = parseInt(computed.getPropertyValue('border-top-width'), 10)
	             + parseInt(computed.getPropertyValue('padding-top'), 10)
	             + field.scrollHeight
	             + parseInt(computed.getPropertyValue('padding-bottom'), 10)
	             + parseInt(computed.getPropertyValue('border-bottom-width'), 10);

	field.style.height = height + 'px';

};

function renderAnswerInputs() {
    if($(this).attr("data-questionType") === "trueFalse") {
        $("#trueFalseAnswers").removeClass("d-none");
        $("#userMultipleChoiceAnswers").addClass("d-none")
    } else if($(this).attr("data-questionType") === "multipleChoice") {
        $("#trueFalseAnswers").addClass("d-none");
        $("#userMultipleChoiceAnswers").removeClass("d-none")
    } else if($(this).attr("data-questionType") === "openEnded") {
       //TODO: Time permitting 
    } 
};

//function to flip the question card
function flipcard (){
    $(".card-question").flip({
        axis: 'x',
    });
};

//funtion to call Trivia DB
function triviaDB (){
    var numOfQuestion = 10;
    var triviaURL = "https://opentdb.com/api.php?amount=" + numOfQuestion; 
    //ajax trivia call to get the answers generated by Trivia DB
    $.ajax({
        url: triviaURL,
        method: "GET"
        }).then(function(response){
        //cardQuestionsContainer.empty();
        for(l=0;l<response.results.length;l++){
            var cardQuestionsContainer = $("#card-questions-container");
            cardQuestionsContainer.append("<div class='card card-question' id='card-question"+l+"'>");
            $("#card-question"+l).append("<div class='front' id='card-front"+l+"'>");
            $("#card-front"+l).append("<div class='card-body' id='card-body-front"+l+"'>");
            $("#card-body-front"+l).append("<h3 class='card-title text-center'>Question "+ (l+1) + "<hr>");
            $("#card-body-front"+l).append("<p class='text-center'>" + response.results[l].question);
            $("#card-body-front"+l).append("<div class='row justify-content-center' id='btn-row-"+l+"'>");
            $("#btn-row-"+l).append("<div class='col-12 d-flex justify-content-center btn-toolbar btn-group-toggle' id='btn-col-"+l+"' data-toggle='buttons'>");
            var answersArr = []; //Mira command
            var correctAns = response.results[l].correct_answer; //Mira command
            answersArr.push(correctAns); //Mira command
            for(j=0; j<response.results[l].incorrect_answers.length; j++){ //Mira command
                    var option = response.results[l].incorrect_answers[j]; //Mira command
                    answersArr.push(option);  //Mira command                   
                } 
                    answersArr.sort(function(a,b){return 0.5-Math.random()});
                for(m=0;m<answersArr.length;m++){
                    $("#btn-col-"+l).append("<label class='btn btn-primary' id='btn-option-"+l+m+"'>");
                    $("#btn-option-"+l+m).append("<input type='radio' name='options' value='"+answersArr[m]+"' id='option'"+m+">"+answersArr[m]);
                }
            $("#card-question"+l).append("<div class='back' id='card-back"+l+"'>");
            $("#card-back"+l).append("<div class='card-body' id='card-body-back"+l+"'>");
            $("#card-back"+l).append("<h3 class='card-title text-center' id='card-title-back"+l+"'>Question "+(l+1)+"<hr>");
            $("#card-back"+l).append("<p class='text-center'>"+response.results[l].question);
            $("#card-back"+l).append("<hr>");
            $("#card-back"+l).append("<h4>"+response.results[l].correct_answer);
            flipcard();                 
        }

    });       
}


    
